### ISSUE TITLE
Apple Silicon (M1) macOS Support?

### ISSUE THREAD

**Issue by yukiarimo** [KwaiVGI/LivePortrait#65] opened 2024-07-09 05:29 UTC
Would like to run this on my Mac ;)

**Comment by rprosenc** [comment] 2024-07-09 06:54
+1

**Comment by mc9625** [comment] 2024-07-09 08:18
+1 :)

**Comment by p6002** [comment] 2024-07-09 21:29
It would be nice if it used these AI cores from the M1 processor.

**Comment by FurkanGozukara** [comment] 2024-07-10 02:19
just published cloud tutorial. mac users can use on cloud services : MassedCompute, RunPod and free Kaggle

https://github.com/KwaiVGI/LivePortrait/issues/78

**https://youtu.be/wG7oPp01COg**

### [**LivePortrait: No-GPU Cloud Tutorial - RunPod, MassedCompute & Free Kaggle Account - Animate Images**](https://youtu.be/wG7oPp01COg)

[![image](https://cdn-uploads.huggingface.co/production/uploads/6345bd89fe134dfd7a0dba40/fvWxGLUrIe5XWqP37OBfU.png)](https://youtu.be/wG7oPp01COg)

**Comment by Zhang-Hailan** [comment] 2024-07-10 03:42
raise question:AssertionError: Torch not compiled with CUDA enabled

**Comment by yukiarimo** [comment] 2024-07-10 06:45
> raise question:AssertionError: Torch not compiled with CUDA enabled

Try to run `export PYTORCH_ENABLE_MPS_FALLBACK=1` in the terminal.

**Comment by Zhang-Hailan** [comment] 2024-07-10 07:07
> > raise question:AssertionError: Torch not compiled with CUDA enabled
> 
> Try to run `export PYTORCH_ENABLE_MPS_FALLBACK=1` in the terminal.

same matter
AssertionError: Torch not compiled with CUDA enabled
<img width="975" alt="image" src="https://github.com/KwaiVGI/LivePortrait/assets/91790220/246240e3-2647-43b1-8524-d252dbadc8d2">

**Comment by hamseHussein** [comment] 2024-07-10 08:09
> Would like to run this on my Mac ;)

there's a simple Mac fork already available, https://github.com/Grant-CP/ComfyUI-LivePortraitKJ-MPS

**Comment by Zhang-Hailan** [comment] 2024-07-10 08:13
> > Would like to run this on my Mac ;)
> 
> there's a simple Mac fork already available, https://github.com/Grant-CP/ComfyUI-LivePortraitKJ-MPS

thank u, bro.

**Comment by yukiarimo** [comment] 2024-07-10 20:08
> > Would like to run this on my Mac ;)
> 
> there's a simple Mac fork already available, https://github.com/Grant-CP/ComfyUI-LivePortraitKJ-MPS

Thanks, but is there ComfyUI only available?

**Comment by mc9625** [comment] 2024-07-11 16:33
OK, after many hours of coding (I am definitely NOT a skilled dev) using Claude 3.5 (...well I told you!!!) I was finally able to achieve some results for Mac OS. Basically I merged the CPU version and the Comfy UI version (plus many code of trials and errors!) and now I am able to run at least python inference.py and get a result. It took roughly less then 2 minutes on my MacBook Pro M1 16gb. Just to compare, the CPU version takes more or less 13 minutes to run the same image.
Gradio still doesn't run, I need to tweak a little bit. And I still suspect that something doesn't work as expected because the final result is cropped instead of the full version. 
I can't share the code because, basically is a mess, but if there is any skilled dev that want to work on Mac OS port, I can confirm that with the MPS support the things get a lot better!!
BTW for comparison it would be interesting to know how much does it takes to run the python inference.py demo on a CUDA powered device.

**Comment by zzzweakman** [comment] 2024-07-13 05:02
Hey there,

I wanted to point out that there's been some impressive work for CPU inference by ONNX model done on https://github.com/KwaiVGI/LivePortrait/issues/126. They've managed to get support for the M1 CPU. You might want to follow their progress as well. Great work is happening there : ） @yukiarimo @rprosenc @mc9625 @p6002 @hamseHussein @Zhang-Hailan

**Comment by zzzweakman** [comment] 2024-07-17 09:12
Thank you for your patience, everyone. We are excited to inform you that LivePortrait now supports macOS with Apple Silicon! You can find more details [here](https://github.com/KwaiVGI/LivePortrait/commit/0f839844f60c72700fe80d380368355c29bf3435).

 @yukiarimo @rprosenc @mc9625 @p6002 @hamseHussein @Zhang-Hailan

**Closed** 2024-07-18 03:43 UTC

**Comment by cleardusk** [comment] 2024-07-18 13:17
> Can someone tell me about the speed of using PyTorch on Mac M1/M2? I've been working on some optimizations recently and will be using Onnxruntime Silicon, and I'd like to compare the speeds.

M1 is about 20x slower than RTX 4090, not an exact value. @warmshao

**Comment by warmshao** [comment] 2024-07-18 14:03
> > Can someone tell me about the speed of using PyTorch on Mac M1/M2? I've been working on some optimizations recently and will be using Onnxruntime Silicon, and I'd like to compare the speeds.
> 
> M1 is about 20x slower than RTX 4090, not an exact value. @warmshao

thanks
